platform :ios, '8.0'

target ‘Sketchily-iOS’ do
  pod 'AFNetworking', '~> 3.0'
  pod 'JSONModel'
  pod 'Bolts'
  pod 'Realm'
  pod 'Reachability'
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Crash'
  pod 'Firebase/Auth'
  pod 'Firebase/Messaging'
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  pod 'FBSDKShareKit'

end
